# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackshift" do
  version "1.0.12"

  on_macos do
    on_intel do
      sha256 "2f30fdbd57798571ecc119d530b2a8f90105c98bb5de9668163b8a826f671daa"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_darwin_amd64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
    on_arm do
      sha256 "30f410c1fa9679218df3f70d588d54d9634b8b5722432d5ea023a20b5b448bd7"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_darwin_arm64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "362f9a4c836a9868ddf09907bc00138f68294f831e286c73e7082e1b46cfd074"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_linux_amd64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
    on_arm do
      sha256 "bb507ebe4233d3cbcf856d958936fe81f9d9f0da5d3f848d6cf7cdf26eb8877c"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_linux_arm64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
  end

  name "stackshift"
  desc "Manage StackShift from the command line"
  homepage "https://stackshift.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackshift"

  # No zap stanza required

end
