# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackshift" do
  version "1.0.14"

  on_macos do
    on_intel do
      sha256 "7bb8e5d40b1ea5ec425c73478a4307eeb5b55bb7395cd4c7ac65b70d2c1fcc3d"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_darwin_amd64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
    on_arm do
      sha256 "1485c8d2b97acb30a103572703b408b6862899ae6330bf75f510f297831e2ecd"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_darwin_arm64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7c458ec5918c2409d7111dc181d48e90584eb7bac8762d097322a2a48e1e29f8"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_linux_amd64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
    on_arm do
      sha256 "175bb5ed884bc5678a35fc25c973c4e53873c37621eb5ea43580621a2fc72b5b"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_linux_arm64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
  end

  name "stackshift"
  desc "Manage StackShift from the command line"
  homepage "https://stackshift.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackshift"

  # No zap stanza required

end
