# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackshift" do
  version "1.0.10"

  on_macos do
    on_intel do
      sha256 "71e93af044da33db98f20f55e16f30c07768bd8ec6ac48b460880ab459410cbc"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_darwin_amd64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
    on_arm do
      sha256 "446f523223627b139644fdacb8a2126718c0cdacecd67763ff3dc29561bbd960"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_darwin_arm64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac0b932f639fcf3ef3cb11ae597810c7f290cab8d52432e98c07a8d287a3e001"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_linux_amd64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
    on_arm do
      sha256 "d1291eec134bd0f91fd95827784557cb5c35fe5d87a4d8f0f81accd3df0d76fd"
      url "https://github.com/stackshiftCloud/stackshift-cli/releases/download/v#{version}/stackshift_linux_arm64.tar.gz",
        verified: "github.com/stackshiftCloud/stackshift-cli/"
    end
  end

  name "stackshift"
  desc "Manage StackShift from the command line"
  homepage "https://stackshift.cloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackshift"

  # No zap stanza required

end
